timezone: Africa/Lagos
version: 1516939968
cookie: PasswordDelayapp
db: bolt.db
os:
path: ./
address: :4444
encryption_keys:
  public: /public.pem
  private: /private.pem

mailer:
  port: 587
  server: smtp.mailgun.org
  username: postmaster@passworddelay.ml
  password: sdsdsd
  fromname: noreply@passworddelay.ml
